// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Sequence item that represents a change on the ping request interface. This is generated by
// monitors (looking at signals inside alert_handler). It is not randomised or driven.

class ping_req_seq_item extends uvm_sequence_item;
  `uvm_object_utils(ping_req_seq_item)

  // Is this ping request for an alert or escalation interface?
  req_type_e m_req_type;

  // The index of the interface that is addressed by the request
  int unsigned m_idx;

  // Is this the start of a request or its end?
  req_stage_e m_req_stage;

  extern function new(string name="");
  extern virtual function void do_print(uvm_printer printer);
endclass

function ping_req_seq_item::new(string name="");
  super.new(name);
endfunction

function void ping_req_seq_item::do_print(uvm_printer printer);
  super.do_print(printer);
  printer.print_string("m_req_type", m_req_type.name());
  printer.print_field_int("m_idx", m_idx, 32, UVM_NORADIX);
  printer.print_string("m_req_stage", m_req_stage.name());
endfunction
