#!/usr/bin/env python3
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
'''Script for scrambling a ROM image'''

import argparse
import re
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import IO, ClassVar

import hjson
from Crypto.Hash import cSHAKE256
from mem import MemChunk, MemFile

from util.design.prince import prince, sbox
from util.design.secded_gen import ecc_encode_some, load_secded_config


class ScramblingMode(Enum):
    ROM0 = "base-rom"
    ROM1 = "second-rom"
    SRAM = "sram"


def parse_scrambling_mode(name: str) -> ScramblingMode:
    for mode in ScramblingMode:
        if mode.value == name:
            return mode
    raise ValueError(f"No known scrambling mode called {name!r}.")


def get_param_map(module: dict) -> dict[str, dict]:
    """Extract a map for the parameters in the parsed dict describing a module.

    This parsed dict should have been generated by topgen, and be an entry in
    the "module" list from one of that tool's output files. The dict will have
    a param_list field, which defines a list of parameters. This function
    returns a map from parameter name to the dictionary describing the
    parameter.
    """
    param_list = module.get('param_list')
    if param_list is None:
        raise ValueError("Module dictionary has no param_list key.")
    if not isinstance(param_list, list):
        raise ValueError("param_list in module dictionary is not a list.")

    # If this dictionary describes an instantiation of module, it might also
    # have a map with the values passed for the module's parameters. This is
    # called 'param_decl'. If there isn't one, default to an empty dictionary.
    param_decl = module.get('param_decl', {})
    if not isinstance(param_decl, dict):
        raise ValueError("param_decl in module dictionary is not a dict.")

    name_to_param: dict[str, dict] = {}
    for param_idx, param in enumerate(param_list):
        if not isinstance(param, dict):
            msg = f"Entry {param_idx} in param_list for module is not a dict."
            raise ValueError(msg)

        param_name = param.get('name')
        if param_name is None:
            msg = f"Entry {param_idx} in param_list for module has no name."
            raise ValueError(msg)

        if not isinstance(param_name, str):
            msg = (f"Name of entry {param_idx} in param_list "
                   "for module is not a string.")
            raise ValueError(msg)

        if param_name in name_to_param:
            msg = (f"Multiple parameters named {param_name} "
                   "in param_list for module.")
            raise ValueError(msg)

        # Grab the default value for the parameter (if defined)
        value = param.get('default')

        # We will use an internal "__value" field to pass the parameter's value
        # to a later function (get_param_cnst). Check that the file didn't
        # define that field.
        if "__value" in param:
            raise RuntimeError(f"Parameter {param_name} in file defines "
                               "(internal) __value field.")

        # Make a shallow copy of the param dictionary (because we are going to
        # want to add "__value" and "param_decl" fields)
        param_dict = dict(param)

        # If this dictionary describes an instantiation of a module, the
        # param_decl map might have a value for the parameter. Store that value
        # under 'param_decl' (referring to its origin) and also use it to set value.
        if param_name in param_decl:
            value = param_decl[param_name]
            param_dict["param_decl"] = value

        # At this point, the parameter should have a value. This will either be
        # the default value or it will have been supplied for this
        # instantiation.
        if value is None:
            raise RuntimeError(f"Parameter {param_name} has no value supplied "
                               "(either as a default or through param_decl).")

        if not (isinstance(value, str) or isinstance(value, int)):
            raise RuntimeError(f"Parameter {param_name} has a supplied value "
                               "that isn't a string or an int.")

        # Set the __value field
        param_dict["__value"] = value

        name_to_param[param_name] = param_dict

    return name_to_param


def parse_as_non_neg_int(val: object, desc: str) -> int:
    """Parse val and return it as an integer.

    If this fails, then raise a ValueError using desc to describe the thing
    that can't be parsed.
    """
    if isinstance(val, int):
        int_val = val
    elif isinstance(val, str):
        # If the value is represented as a SystemVerilog-form bitvector, it
        # will be something like "1'b0" (or, in theory, might be something like
        # "3'100"). Parse that sort of thing, ignoring the width (because we
        # just want the actual value and will zero extend anyway).
        bin_match = re.match(r"[0-9]*'b([01]+)", val)
        if bin_match is not None:
            int_val = int(bin_match.group(1), 2)
        else:
            # In the more general case, the value should look like a C-style
            # literal ("123", "-456", or "0xff"). Python can parse this.
            try:
                int_val = int(val, 0)
            except ValueError:
                msg = (f"Cannot represent parse {desc}, "
                       f"{val!r}, as an integer.")
                raise ValueError(msg) from None
    else:
        raise ValueError(f"Cannot parse {desc}: "
                         "it is not a string or an integer.")

    if int_val < 0:
        msg = (f"Cannot parse {desc} (which is "
               f"{int_val}) as a non-negative integer")
        raise ValueError(msg)

    return int_val


def parse_as_integer_with_width(val: object, width: int, desc: str) -> int:
    """Parse val and return it as an integer with width bits.

    If this fails, then raise a ValueError using desc to describe the thing
    that can't be parsed.
    """
    val_int = parse_as_non_neg_int(val, desc)

    # Check that val is representable with randwidth bits.
    if (val_int >> width) != 0:
        msg = (f"Value for {desc} is {val}, but should be "
               f"representable with {width} bits.")
        raise ValueError(msg)

    return val_int

def get_rand_param_value(name: str,
                         name_to_param: dict[str, dict]) -> tuple[int, int]:
    """Extract a parameter value from name_to_param as (value, width)."""
    param = name_to_param.get(name)
    if param is None:
        msg = f"The param dictionary does not have an entry for '{name}'"
        raise RuntimeError(msg)

    # We expect the parameter to have a width (because it was in a "secrets"
    # hjson file, a format that has them) and that value should be an integer
    # or parseable as an integer.
    if "randwidth" not in param:
        raise ValueError(f"The {name} parameter has no randwidth value.")
    randwidth = parse_as_non_neg_int(param['randwidth'],
                                     f"randwidth for {name} parameter")

    # Get the value that was stashed by get_param_map(). This will be a string
    # or an int (checked in that function). Interpret that value as an integer.
    val = parse_as_integer_with_width(param['__value'],
                                      randwidth,
                                      f"value of {name} parameter")

    return val, randwidth

@staticmethod
def get_bit_param_value(name: str,
                        name_to_param: dict[str, dict]) -> bool:
    """Extract a 1-bit parameter value from name_to_param."""
    param = name_to_param.get(name)
    if param is None:
        msg = f"The param dictionary does not have an entry for '{name}'"
        raise RuntimeError(msg)

    param_type = param.get('type')
    if param_type is None:
        msg = f"The {name} parameter has no type."
        raise RuntimeError(msg)
    if param_type != 'bit':
        msg = f"The {name} parameter does not have type 'bit'."
        raise RuntimeError(msg)

    # Get the value that was stashed by get_param_map(). This will be a string
    # or an int (checked in that function). Interpret it as a 1-bit integer.
    return bool(parse_as_integer_with_width(param['__value'],
                                            1,
                                            f"value of {name} parameter"))

def get_memory_size32(module: dict, memory_key: str) -> int:
    """Get the size of the memory with the given key in the module.

    The size is returned as a number of 32-bit words.
    """
    memories = module.get("memory")
    if memories is None:
        raise ValueError("No value for the memory key in module.")
    if not isinstance(memories, dict):
        raise ValueError("The memory value for the module is not a dict.")

    memory = memories.get(memory_key)
    if memory is None:
        raise ValueError(f"Module has no memory under the key '{memory_key}'.")
    if not isinstance(memory, dict):
        raise ValueError(f"The memory under '{memory_key}' is not a dict.")

    size = memory.get("size")
    if size is None:
        raise ValueError(f"The memory under '{memory_key}' has no size.")
    size_desc = f"The size field for the memory under '{memory_key}'"
    size_int = parse_as_non_neg_int(size, size_desc)

    if size_int % 4:
        raise ValueError(f"The memory under '{memory_key}' has size "
                         f"{size_int}, which is not a multiple of 4 bytes.")

    return size_int // 4

def get_memory_base(module: dict, memory_key: str) -> int:
    base = module.get("base_addrs")
    if base is None:
        raise ValueError(f"Module has no value for base_addrs key.")
    if not isinstance(base, dict):
        raise ValueError(f"Module base_addrs is not a dict.")

    base_for_mem = base.get(memory_key)
    if base_for_mem is None:
        raise ValueError(f"Module doesn't have a base address "
                         f"under key '{memory_key}'.")
    if not isinstance(base_for_mem, dict):
        raise ValueError(f"Base address for key '{memory_key}' is not a dict.")

    mem_base_for_hart = base_for_mem.get("hart")
    if mem_base_for_hart is None:
        raise ValueError(f"The base address under key '{memory_key}' "
                         "is not defined for 'hart'.")

    addr_desc = f"base address seen by hart for memory with key '{memory_key}'"
    return parse_as_non_neg_int(mem_base_for_hart, addr_desc)

@dataclass
class MemoryController:
    ctrl_name: str
    "The name of the module instance."

    memory_type: str
    "The type of the memory (key under which it appears in windows)"

    base: int
    "The base address of the memory as seen by the hart."

    size_words: int
    "The size of the memory in 32-bit words."

    scr_key: int
    "The key used to scramble the memory."

    scr_key_width: int
    "The bit width of the key used to scramble the memory."

    nonce: int
    "The nonce used to scramble the memory."

    nonce_width: int
    "The bit width of the nonce used to scramble the memory."

    scrambling_disabled: bool
    "If true, the memory is not scrambled."

    @staticmethod
    def make_nt_map(from_hjson: dict) -> dict[tuple[str, str], dict]:
        '''Make a map from (type, name) to corresponding element of from_hjson.

        Here, from_hjson is a dictionary parsed from an hjson file generated by
        topgen. This should have a key called module that contains a list of
        dictionaries that describe the modules in the top-level.

        Those dictionaries should have "name" and "type" keys. The return value
        is a map from (name, type) to the dictionary with that name/type pair.
        '''
        module = from_hjson.get("module")
        if module is None:
            raise ValueError("No module key at the top of the dictionary.")
        if not isinstance(module, list):
            raise TypeError("The 'module' item is not a list.")

        ret: dict[tuple[str, str], dict] = {}

        for idx, module_item in enumerate(module):
            if not isinstance(module_item, dict):
                raise TypeError(f"Item {idx} of module list is not a dict.")

            name_item = module_item.get("name")
            if name_item is None:
                raise ValueError(f"No name key in item {idx} of the "
                                 "module list.")
            if not isinstance(name_item, str):
                raise TypeError(f"The name entry for item {idx} of the module "
                                "list is not a string.")

            type_item = module_item.get("type")
            if type_item is None:
                raise ValueError(f"Item {idx} of the module list has name "
                                 f"{name_item} but no type key.")
            if not isinstance(type_item, str):
                raise TypeError(f"The type entry for item {idx} of the module "
                                f"list (name {name_item}) is not a string.")

            key = (name_item, type_item)
            if key in ret:
                raise ValueError(f"Duplicate (name, type) key in file: {key}")

            ret[key] = module_item

        return ret

    @staticmethod
    def from_hjson_paths(mode: ScramblingMode,
                         top_cfg_path: Path,
                         secrets_path: Path) -> "MemoryController":
        """Return a MemoryController for the given mode based on parsed hjson files

        Arguments:
          mode:         The mode for the memory controller

          top_cfg_path: The path to an hjson file generated by topgen that
                        describes a top (like top_<name>.gen.hjson).

          secrets_path: The path to an hjson file generated by topgen with
                        per-module secrets (test example:
                        top_<name>.secrets.testing.gen.hjson)
        """

        with open(secrets_path, "r", encoding='utf-8') as handle:
            secrets = hjson.load(handle, use_decimal=True)
        if not isinstance(secrets, dict):
            raise TypeError(f"File at {secrets_path} doesn't yield a dict.")
        try:
            nt_to_secret_module = MemoryController.make_nt_map(secrets)
        except Exception as e:
            raise RuntimeError(f"Failed to load secrets file "
                               f"from {secrets_path}") from e

        with open(top_cfg_path, "r", encoding='utf-8') as handle:
            top = hjson.load(handle, use_decimal=True)
        if not isinstance(top, dict):
            raise TypeError(f"File at {secrets_path} doesn't yield a dict.")
        try:
            nt_to_top_module = MemoryController.make_nt_map(top)
        except Exception as e:
            raise RuntimeError(f"Failed to load top config "
                               f"from {top_cfg_path}") from e

        # What module can be associated as a memory controller for this mode,
        # and what might the instance be called?
        type_for_mode: str = ""
        names_for_mode: set[str] = set()

        if mode == ScramblingMode.ROM0:
            # If there is only one ROM, the controller is called "rom_ctrl". If
            # there is more than one, the first is called "rom_ctrl0".
            type_for_mode = "rom_ctrl"
            names_for_mode = {"rom_ctrl", "rom_ctrl0"}
            memory_type = "rom"
            key_name = "RndCnstScrKey"
            nonce_name = "RndCnstScrNonce"
        elif mode == ScramblingMode.ROM1:
            type_for_mode = "rom_ctrl"
            names_for_mode = {"rom_ctrl1"}
            memory_type = "rom"
            key_name = "RndCnstScrKey"
            nonce_name = "RndCnstScrNonce"
        else:
            assert mode == ScramblingMode.SRAM
            type_for_mode = "sram_ctrl"
            names_for_mode = {"sram_ctrl_main"}
            memory_type = "ram"
            key_name = "RndCnstSramKey"
            nonce_name = "RndCnstSramNonce"

        for module_name in names_for_mode:
            nt_key = (module_name, type_for_mode)
            top_module = nt_to_top_module.get(nt_key)
            secret_module = nt_to_secret_module.get(nt_key)

            if top_module is not None and secret_module is not None:
                size_words = get_memory_size32(secret_module, memory_type)
                base = get_memory_base(top_module, memory_type)

                # Extract the parameters for the memory controller, which are
                # defined in both top_mem_ctrl and secrets_mem_ctrl and turn
                # them into maps from parameter name to value.
                #
                # If a parameter is defined in both files, the secrets file
                # takes precedence.
                params = (get_param_map(top_module) |
                          get_param_map(secret_module))

                nonce, nonce_width = get_rand_param_value(nonce_name, params)
                scr_key, scr_key_width = get_rand_param_value(key_name, params)
                scrambling_disabled = \
                    get_bit_param_value("SecDisableScrambling", params)

                return MemoryController(module_name,
                                        type_for_mode,
                                        base,
                                        size_words,
                                        scr_key, scr_key_width,
                                        nonce, nonce_width,
                                        scrambling_disabled)

            # To avoid complete confusion, check that we aren't in a situation
            # where just one of the hjson files has an entry that matches this
            # mode's type/name pair.
            if top_module is not None:
                msg = (f"There is en entry in {top_cfg_path} for the "
                       f"(name, type) pair {nt_key}, but no matching "
                       f"entry in {secrets_path}.")
                raise RuntimeError(msg)
            if secret_module is not None:
                msg = (f"There is en entry in {secrets_path} for the "
                       f"(name, type) pair {nt_key}, but no matching "
                       f"entry in {top_cfg_path}.")
                raise RuntimeError(msg)

        # If we get here then there is no matching module in either of the
        # hjson files.
        msg = (f"There is no module described in {top_cfg_path} that can be "
               f"used for secrets mode {mode}.")
        raise RuntimeError(msg)


PRESENT_SBOX4 = [
    0xc, 0x5, 0x6, 0xb,
    0x9, 0x0, 0xa, 0xd,
    0x3, 0xe, 0xf, 0x8,
    0x4, 0x7, 0x1, 0x2
]

PRESENT_SBOX4_INV = [
    0x5, 0xe, 0xf, 0x8,
    0xc, 0x1, 0x2, 0xd,
    0xb, 0x4, 0x6, 0x3,
    0x0, 0x7, 0x9, 0xa
]


def subst_perm_enc(data: int, key: int, width: int, num_rounds: int) -> int:
    '''A model of prim_subst_perm in encrypt mode'''
    assert 0 <= width
    assert 0 <= data < (1 << width)
    assert 0 <= key < (1 << width)

    full_mask = (1 << width) - 1
    bfly_mask = (1 << (2 * (width // 2))) - 1

    for rnd in range(num_rounds):
        data_xor = data ^ key

        # SBox layer
        data_sbox = sbox(data_xor, width, PRESENT_SBOX4)

        # Reverse the vector
        data_rev = 0
        for i in range(width):
            bit = (data_sbox >> i) & 1
            data_rev |= bit << (width - 1 - i)

        # Butterfly
        data_bfly = data_rev & (full_mask & ~bfly_mask)
        for i in range(width // 2):
            # data_bfly[i] = data_rev[2i]
            bit = (data_rev >> (2 * i)) & 1
            data_bfly |= bit << i
            # data_bfly[width/2 + i] = data_rev[2i+1]
            bit = (data_rev >> (2 * i + 1)) & 1
            data_bfly |= bit << (width // 2 + i)

        data = data_bfly

    return data ^ key


def subst_perm_dec(data: int, key: int, width: int, num_rounds: int) -> int:
    '''A model of prim_subst_perm in decrypt mode'''
    assert 0 <= width
    assert 0 <= data < (1 << width)
    assert 0 <= key < (1 << width)

    full_mask = (1 << width) - 1
    bfly_mask = (1 << (2 * (width // 2))) - 1

    for rnd in range(num_rounds):
        data_xor = data ^ key

        # Butterfly
        data_bfly = data_xor & (full_mask & ~bfly_mask)
        for i in range(width // 2):
            # data_bfly[2i] = data_xor[i]
            bit = (data_xor >> i) & 1
            data_bfly |= bit << (2 * i)
            # data_bfly[2i+1] = data_xor[i + width // 2]
            bit = (data_xor >> (i + width // 2)) & 1
            data_bfly |= bit << (2 * i + 1)

        # Reverse the vector
        data_rev = 0
        for i in range(width):
            bit = (data_bfly >> i) & 1
            data_rev |= bit << (width - 1 - i)

        # Inverse SBox layer
        data = sbox(data_rev, width, PRESENT_SBOX4_INV)

    return data ^ key

@dataclass
class Scrambler:
    subst_perm_rounds: ClassVar[int] = 2
    num_rounds_half: ClassVar[int] = 3

    disable: bool
    """If true then scrambling is disabled."""

    nonce: int
    """The nonce used when generating the keystream."""

    nonce_width: int
    """The width of the nonce in bits."""

    key: int
    """The key used for the PRINCE keystream."""

    key_width: int
    """The width of the key in bits."""

    rom_base: int
    """The byte address of the base of ROM"""

    rom_size_words: int
    """The number of 32-bit words in the ROM"""

    hash_file: IO[str]
    """A file stream to which the hash should be written as a C constant."""

    _addr_width: int = field(init=False)
    """The bit-width of addresses"""

    _secded_config: dict[str, object] = field(init=False)
    """A dictionary representation of SECDED configuration (for secded_gen)"""

    def __post_init__(self):
        assert self.nonce_width > 0
        assert self.key_width > 0
        assert 0 <= self.nonce < (1 << self.nonce_width)
        assert 0 <= self.key < (1 << self.key_width)
        assert 0 < self.rom_size_words < (1 << 64)

        self._addr_width = (self.rom_size_words - 1).bit_length()
        self._secded_config = load_secded_config()

    def is_disabled(self) -> bool:
        return self.disable

    @staticmethod
    def from_hjson_paths(top_cfg_path: Path,
                         secrets_path: Path,
                         mode: ScramblingMode,
                         hash_file: IO[str]) -> 'Scrambler':
        mem_ctrl = MemoryController.from_hjson_paths(mode, top_cfg_path, secrets_path)

        return Scrambler(mem_ctrl.scrambling_disabled, mem_ctrl.nonce, mem_ctrl.nonce_width,
                         mem_ctrl.scr_key, mem_ctrl.scr_key_width,
                         mem_ctrl.base, mem_ctrl.size_words, hash_file)

    def flatten(self, mem: MemFile) -> MemFile:
        '''Flatten and pad mem up to the correct size

        This adds 8 trailing zero words as space to store the expected hash.
        These are (obviously!) not the right hash: we inject them properly
        later.

        '''
        digest_size_words = 8
        initial_len = self.rom_size_words - digest_size_words

        flattened = mem.flatten(initial_len)
        assert len(flattened.chunks) == 1
        assert len(flattened.chunks[0].words) == initial_len

        # Add the 8 trailing zero words. We do it here, rather than passing
        # rom_size_words to mem.flatten, to make sure that we see the error if
        # mem is too big.
        flattened.chunks[0].words += [0] * digest_size_words

        return flattened

    def get_keystream(self, log_addr: int, width: int) -> int:
        assert (log_addr >> self._addr_width) == 0
        assert 0 < width <= 64

        data_nonce_width = 64 - self._addr_width
        data_scr_nonce = self.nonce & ((1 << data_nonce_width) - 1)
        to_scramble = (data_scr_nonce << self._addr_width) | log_addr
        full_keystream = int(
            prince(to_scramble, self.key, self.num_rounds_half))

        return full_keystream & ((1 << width) - 1)

    def addr_sp_enc(self, log_addr: int) -> int:
        assert self._addr_width < self.nonce_width
        data_nonce_width = self.nonce_width - self._addr_width
        addr_scr_nonce = self.nonce >> data_nonce_width
        if (self.rom_size_words == 2**self._addr_width):
            # Because the memory depth is exactly the size addressable by _addr_width, we can
            # simply pass the full address through the S&P network.
            sp_width = self._addr_width
            num_chunks = 1
        else:
            # The memory depth is not a power of two. We split the memory into `num_chunks` chunks
            # with a power-of-two depth. Within the chunks, addresses get scrambled with the S&P
            # network. The distribution of the chunks onto the actual memory is determined by the
            # `off_addr` bits of the nonce.
            sp_depth = self.rom_size_words & (-self.rom_size_words)
            num_chunks = self.rom_size_words // sp_depth
            assert num_chunks * sp_depth == self.rom_size_words
            sp_width = (sp_depth - 1).bit_length()
        # Pass the `sp_width` LSBs through the S&P network.
        sp_addr = log_addr & ((1 << sp_width) - 1)
        sp_nonce = addr_scr_nonce & ((1 << sp_width) - 1)
        sp_encrypted_addr = subst_perm_enc(sp_addr, sp_nonce, sp_width,
                                           self.subst_perm_rounds)
        if (self.rom_size_words == 2**self._addr_width):
            encrypted_addr = sp_encrypted_addr
        else:
            # Strip off the top-most `off_width` bits of the address and nonce to compute the chunk
            # offset.
            off_addr = log_addr >> sp_width
            off_nonce = addr_scr_nonce >> sp_width
            # Compute the offset and wrap around if necessary.
            off_encrypted = (off_addr + off_nonce) % num_chunks
            # Stitch the decrypted address together.
            encrypted_addr = (off_encrypted << sp_width) + sp_encrypted_addr
        return encrypted_addr

    def addr_sp_dec(self, phy_addr: int) -> int:
        assert self._addr_width < self.nonce_width
        data_nonce_width = self.nonce_width - self._addr_width
        addr_scr_nonce = self.nonce >> data_nonce_width
        if (self.rom_size_words == 2**self._addr_width):
            # Because the memory depth is exactly the size addressable by _addr_width, we can
            # simply pass the full address through the S&P network.
            sp_width = self._addr_width
            num_chunks = 1
        else:
            # The memory depth is not a power of two. We split the memory into `num_chunks` chunks
            # with a power-of-two depth. Within the chunks, addresses get scrambled with the S&P
            # network. The distribution of the chunks onto the actual memory is determined by the
            # `off_addr` bits of the nonce.
            sp_depth = self.rom_size_words & (-self.rom_size_words)
            num_chunks = self.rom_size_words // sp_depth
            assert num_chunks * sp_depth == self.rom_size_words
            sp_width = (sp_depth - 1).bit_length()
        # Pass the `sp_width` LSBs through the S&P network.
        sp_addr = phy_addr & ((1 << sp_width) - 1)
        sp_nonce = addr_scr_nonce & ((1 << sp_width) - 1)
        sp_decrypted_addr = subst_perm_dec(sp_addr, sp_nonce, sp_width,
                                           self.subst_perm_rounds)
        if (self.rom_size_words == 2**self._addr_width):
            decrypted_addr = sp_decrypted_addr
        else:
            # Strip off the top-most `off_width` bits of the address and nonce to compute the chunk
            # offset.
            off_addr = phy_addr >> sp_width
            off_nonce = addr_scr_nonce >> sp_width
            # Compute the offset and wrap around if necessary. This must be the inverse of the
            # addition performed in addr_sp_enc, i.e. subtraction, so that addr_sp_dec is the
            # true inverse of addr_sp_enc for every nonce value.
            off_decrypted = (off_addr - off_nonce) % num_chunks
            # Stitch the decrypted address together.
            decrypted_addr = (off_decrypted << sp_width) + sp_decrypted_addr
        return decrypted_addr

    def scramble_word(self, width: int, log_addr: int, clr_data: int) -> int:
        '''Scramble clr_data at the given logical address.'''
        keystream = self.get_keystream(log_addr, width)
        return keystream ^ clr_data

    def unscramble_word(self, width: int, log_addr: int, scr_data: int) -> int:
        keystream = self.get_keystream(log_addr, width)
        return keystream ^ scr_data

    def scramble(self, mem: MemFile) -> MemFile:
        assert len(mem.chunks) == 1
        assert len(mem.chunks[0].words) == self.rom_size_words

        width = mem.width

        # Write addr_sp, data_sp for the S&P networks for address and data,
        # respectively. Write clr[i] for unscrambled data word i and scr[i] for
        # scrambled data word i. We need to construct scr[0], scr[1], ...,
        # scr[self.rom_size_words].
        #
        # Then, for all i, we have:
        #
        #   clr[i] = PRINCE(i) ^ scr[addr_sp_enc(i)]
        #
        # Change coordinates by evaluating at addr_sp_dec(i):
        #
        #   clr[addr_sp_dec(i)] = PRINCE(addr_sp_dec(i)) ^ scr[i]
        #
        # so
        #
        #   scr[i] = clr[addr_sp_dec(i)] ^ PRINCE(addr_sp_dec(i))
        #
        # Using the scramble_word helper function, this is:
        #
        #   scr[i] = scramble_word(width, addr_sp_dec(i), clr[addr_sp_dec(i)])

        assert width <= 64

        scrambled = []
        for phy_addr in range(self.rom_size_words):
            log_addr = self.addr_sp_dec(phy_addr)
            assert 0 <= log_addr < self.rom_size_words

            clr_data = mem.chunks[0].words[log_addr]
            assert 0 <= clr_data < (1 << width)

            scrambled.append(self.scramble_word(width, log_addr, clr_data))

        return MemFile(mem.width, [MemChunk(0, scrambled)])

    def add_hash(self, scr_mem: MemFile) -> None:
        '''Calculate and insert a cSHAKE256 hash for scr_mem

        This reads all the scrambled data in logical order, except for the last
        8 words. It then calculates the resulting cSHAKE hash and finally
        inserts that hash (unscrambled) in as the top 8 words.

        '''
        # We only support flat memories of the correct length
        assert len(scr_mem.chunks) == 1
        assert scr_mem.chunks[0].base_addr == 0
        assert len(scr_mem.chunks[0].words) == self.rom_size_words
        assert scr_mem.width == 39

        scr_chunk = scr_mem.chunks[0]

        bytes_per_word = 32 // 8
        num_digest_words = 256 // 32

        # Read out the scrambled data in logical address order
        to_hash = b''
        for log_addr in range(self.rom_size_words - num_digest_words):
            phy_addr = self.addr_sp_enc(log_addr)
            scr_word = scr_chunk.words[phy_addr]
            # Note that a scrambled word with ECC amounts to 39bit. The
            # expression (39 + 7) // 8 calculates the amount of bytes that are
            # required to store these bits.
            to_hash += scr_word.to_bytes((39 + 7) // 8, byteorder='little')

        # Hash it
        hash_obj = cSHAKE256.new(data=to_hash, custom=b'ROM_CTRL')
        digest_bytes = hash_obj.read(bytes_per_word * num_digest_words)
        digest256 = int.from_bytes(digest_bytes, byteorder='little')

        # Chop the 256-bit digest into 32-bit words. These words should never
        # be read "unscrambled": the rom_ctrl checker reads them raw. We can
        # guarantee this by fiddling around with the top 7 bits (which are
        # otherwise ignored) to ensure that they unscramble to words with
        # invalid ECC checksums.
        mask32 = (1 << 32) - 1
        first_digest_idx = self.rom_size_words - num_digest_words
        # Create a file to store the ROM hash.
        print('#include <stdint.h>\n', file = self.hash_file)
        print(f'const uint32_t kRomImageHash[{num_digest_words}] = {{', file = self.hash_file)
        for digest_idx in range(num_digest_words):
            log_addr = first_digest_idx + digest_idx
            w32 = (digest256 >> (32 * digest_idx)) & mask32
            found_mismatch = False

            for chk_bits in range(128):
                w39 = w32 | (chk_bits << 32)
                clr39 = self.unscramble_word(39, log_addr, w39)
                clr32 = clr39 & mask32
                exp39 = ecc_encode_some(self._secded_config, 'inv_hsiao', 32,
                                        [clr32])[0][0]
                if clr39 != exp39:
                    # The checksum doesn't match. Excellent!
                    found_mismatch = True
                    break

            # Surely at least one of the 128 possible choices of top bits
            # should have given us an invalid checksum.
            assert found_mismatch

            phy_addr = self.addr_sp_enc(log_addr)
            scr_chunk.words[phy_addr] = w32
            print(f'  {w32:#08x},', file = self.hash_file)
        print('};', file = self.hash_file)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('top_hjson', type=Path)
    parser.add_argument('secrets_hjson', type=Path)
    parser.add_argument('mode')
    parser.add_argument('infile', type=argparse.FileType('rb'))
    parser.add_argument('outfile', type=argparse.FileType('w'))
    parser.add_argument('hashfile', type=argparse.FileType('w'))

    args = parser.parse_args()
    scrambler = Scrambler.from_hjson_paths(args.top_hjson,
                                           args.secrets_hjson,
                                           parse_scrambling_mode(args.mode),
                                           args.hashfile)

    # Load the input ELF file
    clr_mem = MemFile.load_elf32(args.infile, scrambler.rom_base)

    # Flatten the file, padding with pseudo-random data and ensuring it's
    # exactly scrambler.rom_size_words words long.
    clr_flat = scrambler.flatten(clr_mem)

    # If scrambling is disabled then the memory width is 32 bits, ie no ECC
    # and the data is not scrambled. There is also no hash added.
    if scrambler.is_disabled():
        print("scrambling disabled")
        clr_flat.write_vmem(args.outfile)
        return 0

    # Extend from 32 bits to 39 by adding Hsiao (39,32) ECC bits.
    clr_flat.add_ecc32()
    assert clr_flat.width == 39

    # Scramble the memory
    scr_mem = scrambler.scramble(clr_flat)

    # Insert the expected hash here to the top 8 words
    scrambler.add_hash(scr_mem)

    # Check for collisions
    collisions = scr_mem.collisions()
    if collisions:
        print(
            'ERROR: This combination of ROM contents and scrambling\n'
            '       key results in one or more collisions where\n'
            '       different addresses have the same data.\n'
            '\n'
            '       Looks like we\'ve been (very) unlucky with the\n'
            '       birthday problem. As a work-around, try again after\n'
            '       generating some different RndCnst* parameters.\n',
            file=sys.stderr)
        print(f'{len(collisions)} colliding addresses:', file=sys.stderr)
        for addr0, addr1 in collisions:
            print(f'  {addr0:#010x}, {addr1:#010x}', file=sys.stderr)
        return 1

    scr_mem.write_vmem(args.outfile)
    return 0


if __name__ == '__main__':
    sys.exit(main())
